import { useEffect, useState } from 'react';
import { View, Text, StyleSheet, Pressable, ActivityIndicator, TextInput } from 'react-native';
import { Link, router } from 'expo-router';
import { getSavedProfile, type LocalProfile } from '../lib/profile';
const BG='#0b141a', SURFACE='#111b21', BLUE='#229ed9', MUTED='#8696a0';
export default function Home(){
 const [profile,setProfile]=useState<LocalProfile|null>(null); const [loading,setLoading]=useState(true); const [search,setSearch]=useState('');
 useEffect(()=>{getSavedProfile().then(p=>{setProfile(p);setLoading(false);if(!p) router.replace('/register');});},[]);
 if(loading) return <View style={[s.root,s.center]}><ActivityIndicator color={BLUE}/></View>;
 return <View style={s.root}>
  <View style={s.top}><View><Text style={s.title}>Viet Chat</Text><Text style={s.me}>{profile?.displayName} · {profile?.zapId}</Text></View><Pressable style={s.menu} onPress={()=>router.push('/settings')}><Text style={s.icon}>⋮</Text></Pressable></View>
  <View style={s.search}><Text style={s.searchIcon}>⌕</Text><TextInput value={search} onChangeText={setSearch} placeholder="Search" placeholderTextColor={MUTED} style={s.searchInput}/></View>
  <Link href="/new" asChild><Pressable style={s.chat}><View style={s.avatar}><Text style={s.avatarText}>+</Text></View><View style={s.chatText}><Text style={s.name}>New chat</Text><Text style={s.preview}>Find someone by Viet Chat ID</Text></View></Pressable></Link>
  <View style={s.empty}><Text style={s.emptyTitle}>Your chats</Text><Text style={s.emptyText}>Start a conversation with someone you know.</Text></View>
  <Link href="/new" asChild><Pressable style={s.fab}><Text style={s.fabText}>＋</Text></Pressable></Link>
  <View style={s.tabs}><Link href="/" asChild><Pressable style={s.tab}><Text style={s.active}>Chats</Text></Pressable></Link><Link href="/calls" asChild><Pressable style={s.tab}><Text style={s.tabText}>Calls</Text></Pressable></Link><Link href="/settings" asChild><Pressable style={s.tab}><Text style={s.tabText}>Settings</Text></Pressable></Link></View>
 </View>
}
const s=StyleSheet.create({root:{flex:1,backgroundColor:BG},center:{alignItems:'center',justifyContent:'center'},top:{height:76,backgroundColor:SURFACE,paddingHorizontal:18,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},title:{color:'#fff',fontSize:22,fontWeight:'700'},me:{color:MUTED,fontSize:12,marginTop:2},menu:{width:42,height:42,alignItems:'center',justifyContent:'center'},icon:{color:'#fff',fontSize:28},search:{margin:10,height:44,borderRadius:12,backgroundColor:'#202c33',flexDirection:'row',alignItems:'center',paddingHorizontal:12},searchIcon:{color:MUTED,fontSize:24},searchInput:{flex:1,color:'#fff',fontSize:15,paddingHorizontal:8},chat:{height:78,backgroundColor:SURFACE,flexDirection:'row',alignItems:'center',paddingHorizontal:16,borderBottomWidth:1,borderBottomColor:'#202c33'},avatar:{width:52,height:52,borderRadius:26,backgroundColor:BLUE,alignItems:'center',justifyContent:'center'},avatarText:{color:'#fff',fontSize:22,fontWeight:'700'},chatText:{marginLeft:14,flex:1},name:{color:'#fff',fontSize:16,fontWeight:'600'},preview:{color:MUTED,fontSize:14,marginTop:4},empty:{flex:1,alignItems:'center',justifyContent:'center',padding:35},emptyTitle:{color:'#fff',fontSize:18,fontWeight:'700',marginBottom:8},emptyText:{color:MUTED,textAlign:'center',lineHeight:21},fab:{position:'absolute',right:20,bottom:78,width:58,height:58,borderRadius:29,backgroundColor:BLUE,alignItems:'center',justifyContent:'center'},fabText:{color:'#fff',fontSize:32,fontWeight:'300'},tabs:{height:64,backgroundColor:SURFACE,flexDirection:'row',borderTopWidth:1,borderTopColor:'#202c33'},tab:{flex:1,alignItems:'center',justifyContent:'center'},active:{color:BLUE,fontWeight:'700'},tabText:{color:MUTED,fontWeight:'600'}});
