import { useState } from 'react';
import { View, Text, TextInput, Pressable, StyleSheet, Alert, ActivityIndicator } from 'react-native';
import { router } from 'expo-router';
import { getSavedProfile } from '../lib/profile';
import { supabase } from '../lib/supabase';

export default function New(){
 const [id,setId]=useState(''); const [busy,setBusy]=useState(false);
 const open=async()=>{const value=id.trim().toUpperCase();if(!/^VC-\d{6}$/.test(value)){Alert.alert('Invalid Viet Chat ID','Enter a valid ID such as VC-123456.');return;} if(!supabase){Alert.alert('Connection unavailable','Viet Chat is not connected to its messaging server yet.');return;} setBusy(true); try { const me=await getSavedProfile(); if(!me?.id){Alert.alert('Profile required','Please create your Viet Chat profile first.');return;} const {data:recipient,error}=await supabase.rpc('find_profile_by_zap_id',{p_zap_id:value}); if(error) throw error; if(!recipient?.length){Alert.alert('User not found','No Viet Chat account was found for that ID.');return;} if(recipient[0].id===me.id){Alert.alert('That is your ID','Enter another user's Viet Chat ID.');return;} const {data:conversationId,error:conversationError}=await supabase.rpc('get_or_create_direct_conversation',{p_profile_a:me.id,p_profile_b:recipient[0].id}); if(conversationError) throw conversationError; router.push({pathname:'/chat',params:{id:conversationId,recipientId:recipient[0].id,name:recipient[0].display_name,zapId:recipient[0].zap_id}}); } catch(e){Alert.alert('Could not open chat','Please check your connection and try again.');} finally {setBusy(false);} };
 return <View style={s.root}><Text style={s.title}>New chat</Text><Text style={s.sub}>Find someone using their Viet Chat ID.</Text><TextInput style={s.input} value={id} onChangeText={setId} placeholder="VC-123456" placeholderTextColor="#8696a0" autoCapitalize="characters" autoCorrect={false}/><Pressable disabled={busy} style={[s.button,busy&&s.disabled]} onPress={open}>{busy?<ActivityIndicator color="#fff"/>:<Text style={s.buttonText}>Find user</Text>}</Pressable></View>
}
const s=StyleSheet.create({root:{flex:1,backgroundColor:'#0b141a',padding:22},title:{color:'#fff',fontSize:28,fontWeight:'700',marginTop:35},sub:{color:'#8696a0',fontSize:15,lineHeight:22,marginTop:10},input:{marginTop:28,height:54,borderRadius:12,backgroundColor:'#202c33',color:'#fff',paddingHorizontal:16,fontSize:16},button:{marginTop:14,height:52,borderRadius:12,backgroundColor:'#229ed9',alignItems:'center',justifyContent:'center'},disabled:{opacity:.6},buttonText:{color:'#fff',fontWeight:'700',fontSize:16}});
