'use client'
import { useEffect, useRef, useState } from 'react'
const themes=[{id:'ocean',name:'Ocean Blue',bg:'#0b141a',accent:'#229ed9',bubble:'#005c4b'},{id:'midnight',name:'Midnight',bg:'#090d12',accent:'#2aabee',bubble:'#26394b'},{id:'mint',name:'Mint',bg:'#0b1714',accent:'#21a67a',bubble:'#075e54'},{id:'sunset',name:'Sunset',bg:'#19100c',accent:'#f07845',bubble:'#8a3d20'}]
type Profile={name:string;id:string;uuid:string};type Msg={id:number;text:string;mine:boolean;image?:string}
const supabaseUrl=process.env.NEXT_PUBLIC_SUPABASE_URL||process.env.EXPO_PUBLIC_SUPABASE_URL||'';const supabaseKey=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY||process.env.EXPO_PUBLIC_SUPABASE_ANON_KEY||'';
async function rpc(name:string,args:Record<string,unknown>){if(!supabaseUrl||!supabaseKey)throw new Error('Supabase environment variables are missing');const r=await fetch(`${supabaseUrl}/rest/v1/rpc/${name}`,{method:'POST',headers:{apikey:supabaseKey,Authorization:`Bearer ${supabaseKey}`,'Content-Type':'application/json'},body:JSON.stringify(args)});if(!r.ok)throw new Error(await r.text());return r.json()}
function uuid(){return typeof crypto!=='undefined'&&crypto.randomUUID?crypto.randomUUID():'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,c=>{const r=Math.random()*16|0,v=c==='x'?r:(r&3)|8;return v.toString(16)})}
export default function Home(){const [name,setName]=useState('');const [created,setCreated]=useState(false);const [id,setId]=useState('');const [uuidValue,setUuidValue]=useState('');const [tab,setTab]=useState<'chats'|'contacts'|'profile'|'settings'>('chats');const [theme,setTheme]=useState(themes[0]);const [showThemes,setShowThemes]=useState(false);const [search,setSearch]=useState(false);const [chatOpen,setChatOpen]=useState(false);const [message,setMessage]=useState('');const [messages,setMessages]=useState<Msg[]>([]);const [call,setCall]=useState<'voice'|'video'|null>(null);const [mic,setMic]=useState(false);const [camera,setCamera]=useState(false);const [recipient,setRecipient]=useState({name:'Viet Chat',id:''});const [lookupId,setLookupId]=useState('');const [lookupBusy,setLookupBusy]=useState(false);const [lookupError,setLookupError]=useState('');const videoRef=useRef<HTMLVideoElement>(null);const fileRef=useRef<HTMLInputElement>(null);
useEffect(()=>{try{const raw=localStorage.getItem('viet_chat_profile');if(raw){const p=JSON.parse(raw) as Profile;setName(p.name);setId(p.id);setUuidValue(p.uuid);setCreated(true)}}catch{}},[])
useEffect(()=>{if(!call)return;let stream:MediaStream|undefined;const start=async()=>{try{stream=await navigator.mediaDevices.getUserMedia({audio:true,video:call==='video'});if(videoRef.current&&stream)videoRef.current.srcObject=stream;setMic(true);setCamera(call==='video')}catch{setMic(false);setCamera(false)}};start();return()=>stream?.getTracks().forEach(t=>t.stop())},[call])
async function create(){const n=name.trim();if(!n)return;try{const raw=localStorage.getItem('viet_chat_profile');const p:Profile=raw?JSON.parse(raw):{name:n,id:`VC-${Math.floor(100000+Math.random()*900000)}`,uuid:uuid()};p.name=n;await rpc('register_viet_chat_profile',{p_id:p.uuid,p_zap_id:p.id,p_display_name:p.name});localStorage.setItem('viet_chat_profile',JSON.stringify(p));setName(p.name);setId(p.id);setUuidValue(p.uuid);setCreated(true)}catch{const p:Profile={name:n,id:id||`VC-${Math.floor(100000+Math.random()*900000)}`,uuid:uuid()};localStorage.setItem('viet_chat_profile',JSON.stringify(p));setName(n);setId(p.id);setUuidValue(p.uuid);setCreated(true)}}
async function findUser(){const value=lookupId.trim().toUpperCase();if(!/^VC-\d{6}$/.test(value)){setLookupError('Enter a valid ID such as VC-123456.');return}setLookupBusy(true);setLookupError('');try{const rows=await rpc('find_profile_by_zap_id',{p_zap_id:value});const person=rows?.[0];if(!person){setLookupError('No user was found with that Viet Chat ID.');return}if(person.id===uuidValue){setLookupError('That is your own ID. Enter another user.');return}const conv=await rpc('get_or_create_direct_conversation',{p_profile_a:uuidValue,p_profile_b:person.id});setRecipient({name:person.display_name,id:person.zap_id});setMessages([]);setChatOpen(true);setLookupId('');}catch{setLookupError('Unable to find this user. Check your connection and try again.')}finally{setLookupBusy(false)}}
function send(){const t=message.trim();if(!t)return;setMessages(v=>[...v,{id:Date.now(),text:t,mine:true}]);setMessage('')}
function photo(e:React.ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;setMessages(v=>[...v,{id:Date.now(),text:'',mine:true,image:URL.createObjectURL(f)}]);e.target.value=''}
function copy(text:string){navigator.clipboard?.writeText(text)}
if(!created)return <main className="shell"><section className="card"><div className="logo">Viet Chat</div><h1>Private conversations, made simple.</h1><p className="muted">Create your profile and start chatting.</p><label className="field"><span>Display name</span><input value={name} onChange={e=>setName(e.target.value)} placeholder="Your name" maxLength={40}/></label><button className="primary" disabled={!name.trim()} onClick={create}>Continue</button></section></main>
if(call)return <main className="callScreen"><div className="callTop"><button onClick={()=>setCall(null)}>‹</button><span>{call==='video'?'Video call':'Voice call'}</span><button onClick={()=>setCall(null)}>×</button></div>{call==='video'?<video ref={videoRef} autoPlay muted playsInline className="callVideo"/>:<div className="callAvatar">{recipient.name[0]?.toUpperCase()}</div>}<div className="callName">{recipient.name}</div><div className="callStatus">{call==='video'?'Camera and microphone active':'Microphone active'} · calling</div><div className="callControls"><button onClick={()=>setMic(v=>!v)}>{mic?'🎙':'🔇'}</button>{call==='video'&&<button onClick={()=>setCamera(v=>!v)}>{camera?'▣':'□'}</button>}<button className="endCall" onClick={()=>setCall(null)}>☎</button></div></main>
if(chatOpen)return <main className="chatApp"><header className="chatHead"><button className="backBtn" onClick={()=>setChatOpen(false)}>‹</button><div className="avatar">{recipient.name[0]?.toUpperCase()}</div><div className="chatTitle"><strong>{recipient.name}</strong><span>{recipient.id||'online'}</span></div><div className="callActions"><button onClick={()=>setCall('voice')}>☎</button><button onClick={()=>setCall('video')}>▣</button></div></header><section className="messages">{messages.length===0&&<div className="chatWelcome">Start your conversation with {recipient.name}</div>}{messages.map(m=><div key={m.id} className={`bubble ${m.mine?'outgoing':'incoming'}`} onContextMenu={e=>{e.preventDefault();if(m.text)copy(m.text)}}>{m.image?<img src={m.image} className="messageImage" alt="Shared photo"/>:<span>{m.text}</span>}</div>)}</section><div className="composer"><input ref={fileRef} type="file" accept="image/*" hidden onChange={photo}/><button className="attach" onClick={()=>fileRef.current?.click()}>＋</button><input value={message} onChange={e=>setMessage(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="Message"/><button className="send" onClick={send}>➤</button></div></main>
return <main className="mobileApp darkApp" style={{'--app-accent':theme.accent,'--chat-bg':theme.bg,'--bubble':theme.bubble} as React.CSSProperties}><header className="appHeader"><div><div className="logo small">Viet Chat</div><div className="muted">{tab[0].toUpperCase()+tab.slice(1)}</div></div><button className="iconButton" onClick={()=>setSearch(v=>!v)}>⌕</button></header>{search&&<input autoFocus className="searchBar" placeholder="Search chats, contacts and messages"/>}{tab==='chats'&&<section className="chatList"><button className="chatRow" onClick={()=>setTab('contacts')}><div className="avatar">+</div><div className="chatInfo"><strong>New conversation</strong><span>Find someone by Viet Chat ID</span></div></button><button className="chatRow" onClick={()=>{setRecipient({name:'Viet Chat',id:''});setChatOpen(true)}}><div className="avatar">V</div><div className="chatInfo"><strong>Viet Chat</strong><span>{messages[messages.length-1]?.text||'Start chatting'}</span></div><time>Now</time></button></section>}{tab==='contacts'&&<section className="panel"><h2>Find someone</h2><p className="muted">Enter their Viet Chat ID and open their profile instantly.</p><input className="wideInput" value={lookupId} onChange={e=>setLookupId(e.target.value)} placeholder="VC-123456" autoCapitalize="characters"/><button className="primary" disabled={lookupBusy} onClick={findUser}>{lookupBusy?'Finding…':'Find user'}</button>{lookupError&&<p className="lookupError">{lookupError}</p>}</section>}{tab==='profile'&&<section className="panel profilePanel"><div className="bigAvatar">{name[0]?.toUpperCase()}</div><h2>{name}</h2><p className="muted">Your Viet Chat ID</p><div className="idBox">{id}</div></section>}{tab==='settings'&&<section className="panel"><h2>Appearance</h2><button className="settingRow" onClick={()=>setShowThemes(v=>!v)}>Chat themes <span>{theme.name} ›</span></button>{showThemes&&<div className="themeGrid">{themes.map(t=><button key={t.id} className="themeCard" style={{background:t.bg,borderColor:t.id===theme.id?t.accent:'#34414a'}} onClick={()=>{setTheme(t);setShowThemes(false)}}><span style={{background:t.accent}}></span><strong>{t.name}</strong></button>)}</div>}<button className="settingRow">Notifications <span>›</span></button><button className="settingRow">Privacy <span>›</span></button></section>}<nav className="bottomNav"><button className={tab==='chats'?'active':''} onClick={()=>setTab('chats')}>Chats</button><button className={tab==='contacts'?'active':''} onClick={()=>setTab('contacts')}>Contacts</button><button className={tab==='profile'?'active':''} onClick={()=>setTab('profile')}>Profile</button><button className={tab==='settings'?'active':''} onClick={()=>setTab('settings')}>Settings</button></nav></main>}
