'use client'
import { useEffect, useState } from 'react'
const themes=[{id:'ocean',name:'Ocean Blue',bg:'#0b141a',accent:'#229ed9',bubble:'#005c4b'},{id:'midnight',name:'Midnight',bg:'#090d12',accent:'#2aabee',bubble:'#26394b'},{id:'mint',name:'Mint',bg:'#0b1714',accent:'#21a67a',bubble:'#075e54'},{id:'sunset',name:'Sunset',bg:'#19100c',accent:'#f07845',bubble:'#8a3d20'}]
type Profile={name:string;id:string};type Msg={id:number;text:string;mine:boolean;image?:string}
export default function Home(){const [name,setName]=useState('');const [created,setCreated]=useState(false);const [id,setId]=useState('');const [tab,setTab]=useState<'chats'|'contacts'|'profile'|'settings'>('chats');const [theme,setTheme]=useState(themes[0]);const [showThemes,setShowThemes]=useState(false);const [search,setSearch]=useState(false);const [chatOpen,setChatOpen]=useState(false);const [message,setMessage]=useState('');const [messages,setMessages]=useState<Msg[]>([{id:1,text:'Welcome to Viet Chat',mine:false},{id:2,text:'Hi 👋',mine:true}]);
useEffect(()=>{const raw=localStorage.getItem('viet_chat_profile');if(raw){const p=JSON.parse(raw) as Profile;setName(p.name);setId(p.id);setCreated(true)}},[])
function create(){const n=name.trim();if(!n)return;const raw=localStorage.getItem('viet_chat_profile');const p:Profile=raw?JSON.parse(raw):{name:n,id:`VC-${Math.floor(100000+Math.random()*900000)}`};p.name=n;localStorage.setItem('viet_chat_profile',JSON.stringify(p));setName(p.name);setId(p.id);setCreated(true)}
function send(){const t=message.trim();if(!t)return;setMessages(v=>[...v,{id:Date.now(),text:t,mine:true}]);setMessage('')}
if(!created)return <main className="shell"><section className="card"><div className="logo">Viet Chat</div><h1>Private conversations, made simple.</h1><p className="muted">Create your profile and start chatting.</p><label className="field"><span>Display name</span><input value={name} onChange={e=>setName(e.target.value)} placeholder="Your name" maxLength={40}/></label><button className="primary" disabled={!name.trim()} onClick={create}>Continue</button></section></main>
if(chatOpen)return <main className="chatApp"><header className="chatHead"><button className="backBtn" onClick={()=>setChatOpen(false)}>‹</button><div className="avatar">V</div><div className="chatTitle"><strong>Viet Chat</strong><span>online</span></div><div className="callActions"><button onClick={()=>alert('Voice call ready for native mobile connection')}>☎</button><button onClick={()=>alert('Video call ready for native mobile connection')}>▣</button></div></header><section className="messages">{messages.map(m=><button key={m.id} className={`bubble ${m.mine?'outgoing':'incoming'}`} onContextMenu={e=>{e.preventDefault();navigator.clipboard?.writeText(m.text)}}>{m.text}</button>)}</section><div className="composer"><button className="attach" onClick={()=>alert('Photo picker will open in the native mobile app')}>＋</button><input value={message} onChange={e=>setMessage(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')send()}} placeholder="Message"/><button className="send" onClick={send}>➤</button></div></main>
return <main className="mobileApp darkApp" style={{'--app-accent':theme.accent,'--chat-bg':theme.bg,'--bubble':theme.bubble} as React.CSSProperties}><header className="appHeader"><div><div className="logo small">Viet Chat</div><div className="muted">{tab[0].toUpperCase()+tab.slice(1)}</div></div><button className="iconButton" onClick={()=>setSearch(v=>!v)}>⌕</button></header>{search&&<input autoFocus className="searchBar" placeholder="Search chats, contacts and messages"/>}{tab==='chats'&&<section className="chatList"><button className="chatRow" onClick={()=>setTab('contacts')}><div className="avatar">+</div><div className="chatInfo"><strong>New conversation</strong><span>Start a direct chat</span></div></button><button className="chatRow" onClick={()=>setChatOpen(true)}><div className="avatar">V</div><div className="chatInfo"><strong>Viet Chat</strong><span>{messages[messages.length-1]?.text||'Start chatting'}</span></div><time>Now</time></button></section>}{tab==='contacts'&&<section className="panel"><h2>Find someone</h2><p className="muted">Enter a Viet Chat ID to open a direct conversation.</p><input className="wideInput" placeholder="VC-123456"/><button className="primary">Open chat</button></section>}{tab==='profile'&&<section className="panel profilePanel"><div className="bigAvatar">{name[0]?.toUpperCase()}</div><h2>{name}</h2><p className="muted">Your Viet Chat ID</p><div className="idBox">{id}</div></section>}{tab==='settings'&&<section className="panel"><h2>Appearance</h2><button className="settingRow" onClick={()=>setShowThemes(v=>!v)}>Chat themes <span>{theme.name} ›</span></button>{showThemes&&<div className="themeGrid">{themes.map(t=><button key={t.id} className="themeCard" style={{background:t.bg,borderColor:t.id===theme.id?t.accent:'#34414a'}} onClick={()=>{setTheme(t);setShowThemes(false)}}><span style={{background:t.accent}}></span><strong>{t.name}</strong></button>)}</div>}<button className="settingRow">Notifications <span>›</span></button><button className="settingRow">Privacy <span>›</span></button></section>}<nav className="bottomNav"><button className={tab==='chats'?'active':''} onClick={()=>setTab('chats')}>Chats</button><button className={tab==='contacts'?'active':''} onClick={()=>setTab('contacts')}>Contacts</button><button className={tab==='profile'?'active':''} onClick={()=>setTab('profile')}>Profile</button><button className={tab==='settings'?'active':''} onClick={()=>setTab('settings')}>Settings</button></nav></main>}
